"""add papers.error

Revision ID: 1728043a9298
Revises: 7f3a91c204be
Create Date: 2026-08-05 07:24:15.137660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1728043a9298'
down_revision: Union[str, None] = '7f3a91c204be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'error')
    # ### end Alembic commands ###
